# Generated by Django 5.0.3 on 2024-04-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identity_number', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
